version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
- package-ecosystem: bun
  directory: "www/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "0 8 * * 1/2" # once every two weeks
  open-pull-requests-limit: 10
