[graph]
all-features = true
targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "x86_64-unknown-linux-musl" },
]

[licenses]
allow = [
  "AGPL-3.0-only",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]
confidence-threshold = 0.8
exceptions = [{ name = "webpki-roots", allow = ["CDLA-Permissive-2.0"] }]

[[licenses.clarify]]
crate = "atrium-codegen"
expression = "MIT"
license-files = []

[[licenses.clarify]]
crate = "atrium-lex"
expression = "MIT"
license-files = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
  "RUSTSEC-2023-0071", # rsa - side-channel attack infeasible, no patches
  "RUSTSEC-2024-0436", # paste - unmaintained, ratatui and other core crates depend on this
  "RUSTSEC-2024-0320", # yaml-rust - unmaintained, tui-markdown depends on this, TODO: eliminate, we already depend on yaml-rust2
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = ["openssl"]
skip-tree = ["atrium-codegen"]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
